# Курсовая работа по дисциплине СиАОД №1

## Выполнила студентка группы БСТ1903 Мисевич И.М.


### Задание 1. «Треугольник с максимальным периметром»
Массив A состоит из целых положительных чисел - длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно
составить треугольник с положительной площадью - функция возвращает 0.

In [34]:
def Perimetr (a, b, c):
    if (a+b)>c and (a+c)>b and (b+c)>a:
        return int(a+b+c)
    else:
        return 0
#
length=int(input('Введите длину массива '))
mas=[]
for i in range(length): 
    mas.append(int(input())) ##добавление целого цикла
mas=sorted(mas, reverse=True) ##сортировка по убыванию
print(mas)
for i in range(len(mas)-2):
    if Perimetr(mas[i], mas[i+1], mas[i+2])>0:
        print("Периметр = ", Perimetr(mas[i], mas[i+1], mas[i+2]))
        break

Введите длину массива 4
3
2
3
4
[4, 3, 3, 2]
Периметр =  10


### Задание 2. «Максимальное число»
Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы
вместе они образовали максимально возможное число.

In [38]:
def check(a,b):
    one=str(a)+str(b)
    two=str(b)+str(a)
    if int(one)>int(two):
        return True
    else:
        return False
    
def nums(massline):
    length=len(massline)
    l=length
    while l>0:
        for i in range(length-l):
            j=i
            while j>=0 and check(massline[j+l], massline[j]):
                massline[j], massline[j+l]=massline[j+l], massline[j]
                j=j-l
        l=int(l/2)
    strr=""
    for i in range(len(massline)):
        strr=strr+" "+str(massline[i])
    return strr

mas1= [3,30,34,5,9]

print(nums(mas1))


 9 5 34 3 30


### Задание 3. «Сортировка диагоналей в матрице»
Дана матрица mat размером m * n, значения - целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу

In [8]:
import numpy ##многомерные массивы
def mat(n, m):
    for i in range(n):
        for j in range(m):
            yield i, j ##1ое значение цикла
m, n= map(int, input('Введите m и n: ').split(' ')) ##функция к каждому элементу объекта
massiv = numpy.random.random_integers(0, 20, size=(m, n))
print(massiv)
for i, j in mat(len(massiv[0]), len(massiv)):
    k=j
    l=i
    while k<len(massiv[0]) and l<len(massiv):
        if massiv[i][j]>massiv[l][k]:
            massiv[i][j], massiv[l][k]=massiv[l][k], massiv[i][j]
        k=k+1
        l=l+1
            
print("\n\n") ##печать строк
print(massiv)

Введите m и n:4 4
[[19 13  7  7]
 [ 1 20 20  1]
 [12 11  7 10]
 [19  2 13 10]]



[[ 7 10  1  7]
 [ 1 10 13  7]
 [ 2 11 19 20]
 [19 12 13 20]]


<ipython-input-8-a8165d67f7f2>:7: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  massiv = numpy.random.random_integers(0, 20, size=(m, n))


### Задание 4. «Объединение отрезков»
Дан массив отрезков intervals, в котором intervals[i] = [start_i, end_ i], некоторые
отрезки могут пересекаться. Напишите функцию, которая объединяет все пересекающиеся отрезки в один и возвращает новый массив непересекающихся отрезков.

In [7]:
def intervals(interv):
    interv.sort()
    i=0
    while i <len(interv)-1:
        if interv[i][1]>=interv[i+1][0]:
            a=interv.pop(0) ##удаляет и возвращает последний эл.
            b=interv.pop(0)
            interv.insert(0, [a[0],b[1]]) ##добавляет указанный элемент в список на указанную позицию
        else:
            i+=1            
    return interv

intervals( [[1,3],[2,6],[8,10],[15,18]])

[[1, 6], [8, 10], [15, 18]]

### Задание 5. «Стопки монет»
На столе стоят 3n стопок монет. Вы и ваши друзья Алиса и Боб забираете стопки монет по
следующему алгоритму:
1. Вы выбираете 3 стопки монет из оставшихся на столе.
2. Алиса забирает себе стопку с максимальным количеством монет.
3. Вы забираете одну из двух оставшихся стопок.
4. Боб забирает последнюю стопку.
5. Если еще остались стопки, то действия повторяются с первого шага.
Дан массив целых положительных чисел piles. Напишите функцию, возвращающую максимальное число монет, которое вы можете получить.

In [6]:
def piles(arr):
    arr.sort()
    a=len(arr)//3
    s=0
    while a<len(arr):
        s=s+arr[a]
        a=a+2
    return (s)

piles (  [2,4,1,2,7,8])

9

### Задание 6. «Шарики и стрелы»
Некоторые сферические шарики распределены по двухмерному пространству. Для каждого
шарика даны x-координаты начала и конца его горизонтального диаметра. Так как пространство
двумерно, то y-координаты не имеют значения в данной задаче. Координата x_start всегда меньше
x_end.
Стрелу можно выстрелить строго вертикально (вдоль y-оси) из разных точек x-оси. Шарик
с координатами x_start и x_end уничтожается стрелой, если она была выпущена из такой позиции
x, что x_start ⩽ x ⩽ x_end. Когда стрела выпущена, она летит в пространстве бесконечное время
(уничтожая все шарики на пути).
Дан массив points, где points[i] = [x_start, x_end]. Напишите функцию, возвращающую минимальное количество стрел, которые нужно выпустить, чтобы уничтожить все шарики.

In [16]:
class points:
    def __init__(self, mass):
        self.mass=mass
        self.count=1
    
    def search(self):
        if len(self.mass)==0:
            self.count=0
        else:
            m=0
            for i in range(len(self.mass)):
                self.mass.sort() ##возрастание по 1ому числу
            print(self.mass)
            for i in range(len(self.mass)-1):
                if self.mass[m][1]<self.mass[i+1][0]:##если не совпадает, то +стрела
                    self.count=self.count+1
                    m=i+1
                elif self.mass[m][0]<=self.mass[i+1][0] and self.mass[m][1]>=self.mass[i+1][1]:
                       m=i+1
                    
        return self.count
            
mass= [[10,16],[2,8],[1,6],[7,12]]         
a=points(mass)
print(a.search())

[[1, 6], [2, 8], [7, 12], [10, 16]]
2


### Задание 7.
Даны две строки: s1 и s2 с одинаковым размером.
Проверьте, может ли
некоторая перестановка строки s1 “победить” некоторую перестановку
строки s2 или наоборот.
Строка x может “победить” строку y (обе имеют размер n), если x[i]> = y
[i] (в алфавитном порядке) для всех i от 0 до n-1.


In [21]:
def zadanie7(s1, s2):
    if len(s1)!=len(s2):
        return False
    st1=list(s1)
    st2=list(s2)
    l=len(st1)
    st1.sort()
    st2.sort()
    i=0
    while i<l and st1[i]==st2[i]:
        i+=1
    if i == l:
        return True
    if st1[i]>st2[i]:
        for k in range(len(st1)):
            if(st1[k]<st2[k]):
                return False
        return True
    else:
        for k in range(len(st2)):
            if(st2[k]<st1[k]):
                return False
        return True                
zadanie7('abc','xya')

True

### Задание 8.
Дана строка s. Вернуть самую длинную полиндромную подстроку в s.


In [39]:
def isPalindrome(word):
    word = word.lower()
    word1 = ''.join(reversed(word))
    if word1 == word:
        return True
    return False
  
    
def longestPalindrome(s):
    max = 1
    ans = s[0]
    for a in range(len(s) - 1):
        word = s[a]
        for b in range(a+1, len(s)):
            word += s[b]
            if isPalindrome(word):
                l = len(word)
                if l > max:
                    max = l
                    ans = word
    return ans

print(longestPalindrome('babad'))
print(longestPalindrome('cbbd'))

bab
bb


### Задание 9.
Вернуть количество отдельных непустых подстрок текста, которые могут
быть записаны как конкатенация некоторой строки с самой собой (т.е. она
может быть записана, как a + a, где a - некоторая строка).

In [40]:
def isConcatenationPossible(word,s):
    for a in range(len(s) - 1):
        guess = s[a]
        for b in range(a+1, len(s)):
            guess += s[b]
            if guess == word * 2:
                return True
    return False


def numOfConcatenationStrings(s):
    count = 0
    mem = []
    for a in range(len(s) - 1):
        guess = s[a]
        if isConcatenationPossible(guess,s):
                if guess not in mem:
                    count += 1
                    mem.append(guess)
        for b in range(a+1, len(s)):
            guess += s[b]
            if isConcatenationPossible(guess,s):
                if guess not in mem:
                    count += 1
                    mem.append(guess)
    return count

print(numOfConcatenationStrings('abcabcabc'))

3


### Вывод
В ходе курсовой работы нами было реализовано решение некоторых типов задач.